export const glbFiles = [
    'src/models/floor0.glb',
    'src/models/floor1.glb',
    'src/models/floor2.glb',
    'src/models/floor3.glb',
    'src/models/floor4.glb',
    'src/models/floor5.glb',
    'src/models/floor6.glb',
    'src/models/floor7.glb',
    'src/models/floor8.glb',
    'src/models/floor9.glb',
    'src/models/floor10.glb',
    'src/models/floor11.glb',
    'src/models/floor12.glb',
    'src/models/floor13.glb',
    'src/models/floor14.glb',
    'src/models/floor15.glb',
    'src/models/floor15.glb',
    'src/models/floor15.glb',
    'src/models/floor15.glb',
    'src/models/floor15.glb',
    'src/models/test4.glb',
    'src/models/numbers.glb',
];


export const VertFloors = [
    'src/models/vertfloor1.glb',
    'src/models/vertfloor2.glb',
    'src/models/vertfloor3.glb',
    'src/models/vertfloor4.glb',
    'src/models/vertfloor5.glb',
    'src/models/vertfloor6.glb',
    'src/models/vertfloor7.glb',
    'src/models/vertfloor8.glb',
    'src/models/vertfloor9.glb',
    'src/models/vertfloor10.glb',
    'src/models/vertfloor11.glb',
    'src/models/vertfloor12.glb',
    'src/models/vertfloor13.glb',
    'src/models/vertfloor14.glb',
    'src/models/vertfloor15.glb',
    'src/models/vertfloor16.glb',
    'src/models/vertfloor17.glb',
    'src/models/vertfloor18.glb',
    'src/models/vertfloor19.glb',
    'src/models/vertfloor20.glb',
];



